var linkt = "tasker://secondary?text="
var intview = intent("android.intent.action.VIEW");

var wr = "wiersze"
var wrbn = libByName(wr)
var hp = "Haczów przestrzenie"
var hpbn = libByName(hp)
var zt = "zadania terminarz zajęć prac zadań zadania"
var ztbn = libByName(zt)
var hk = "Haczów katalog"
var hkbn = libByName(hk)
var ma = "metalowe artykuły"
var mabn = libByName(ma)
var tc = "techniczna"
var tcbn = libByName(tc)
var ps = "PRODUKTY SPOŻYWCZE"
var psbn = libByName(ps)
var rt = "RUTYNY"
var rtbn = libByName(rt)
var an = "angielski"
var anbn = libByName(an)
var lw = "ludzie w miłości kontaktujący się"
var lwbn = libByName(lw)
var pr  = "przepisy"
var prbn  = libByName(pr)
var lk = "lektury"
var lkbn  = libByName(lk)
var sm = "samochód"
var smbn = libByName(sm)
var sc = "sukcesy cuda"
var scbn = libByName(sc)
var gc = "garderoba ubrania ciuchy"
var gcbn = libByName(gc)
var pp = "plan posiłków"
var ppbn = libByName(pp)
var bw = "budżet wydatki przychody zarządzanie"
var bwbn = libByName(bw)
var cf = "ćwiczenia fitness youtube musepic"
var cfbn = libByName(cf)
var ag = "agenda memento harmonogram terminarz kalendarz zadania"
var agbn = libByName(ag)
var zb = "życie ukryte w Bogu Ojcu"
var zbbn =libByName(zb)
var mo = "mój ogród"
var mobn = libByName(mo)
var wi = "wiara"
var wibn = libByName(wi)
var tm = "tabliczka mnożenia"
var tmbn = libByName(tm)
var tt = "time tracking"
var ttbn = libByName(tt)
var lj = "lokalizacje adresy"
var ljbn = libByName(lj)
var dz = "dziennik"
var dzbn = libByName(dz)
var rk = "Rzeszów katalog"
var rkbn = libByName(rk)
var wb = "waga baza danych"
var wbbn = libByName(wb)
var ic = "informacje"
var icbn = libByName(ic)
var sp = "SPOTKANIA"
var spbn = libByName(sp)
var pt = "programy telewizyjne"
var ptbn = libByName(pt)
var kk = "kody kreskowe"
var kkbn = libByName(kk)
var mm = "muzo muzyka"
var mmbn = libByName(mm)
var tk = "teorie kognitywne"
var tkbn = libByName(tk)
var sl = "stan liczników waga kilometry"
var slbn = libByName(sl)
var sb = "Słowo Boże"
var sbbn = libByName(sb)